### ISSUE TITLE
AttributeError: 'Elk' object has no attribute 'callback_add'

### ISSUE THREAD

**Issue by jshank** [BioSehnsucht/ha-elkm1#7]
ha-elkm1 version: 86f83e455755027935e588f648d1e52ebdd4ff17
Home Assistant 0.65.6 (official docker container)

Configuration:

```
elkm1:
  host: socket://10.1.10.21:2101
```
Generates the following startup error

```
hass_1       | 2018-03-27 12:09:20 ERROR (MainThread) [homeassistant.setup] Error during setup of component elkm1
hass_1       | Traceback (most recent call last):
hass_1       |   File "/usr/src/app/homeassistant/setup.py", line 145, in _async_setup_component
hass_1       |     component.setup, hass, processed_config)
hass_1       |   File "/usr/local/lib/python3.6/asyncio/futures.py", line 327, in __iter__
hass_1       |     yield self  # This tells Task to wait for completion.
hass_1       |   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
hass_1       |     future.result()
hass_1       |   File "/usr/local/lib/python3.6/asyncio/futures.py", line 243, in result
hass_1       |     raise self._exception
hass_1       |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
hass_1       |     result = self.fn(*self.args, **self.kwargs)
hass_1       |   File "/usr/src/app/homeassistant/components/elkm1.py", line 167, in setup
hass_1       |     pyelk_instance.callback_add(bound_event_callback)
hass_1       | AttributeError: 'Elk' object has no attribute 'callback_add'
hass_1       | 2018-03-27 12:09:20 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1522177760.4642408, level=ERROR, message=Error during setup of component elkm1, exception=Traceback (most recent call last):
hass_1       |   File "/usr/src/app/homeassistant/setup.py", line 145, in _async_setup_component
hass_1       |     component.setup, hass, processed_config)
hass_1       |   File "/usr/local/lib/python3.6/asyncio/futures.py", line 327, in __iter__
hass_1       |     yield self  # This tells Task to wait for completion.
hass_1       |   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
hass_1       |     future.result()
hass_1       |   File "/usr/local/lib/python3.6/asyncio/futures.py", line 243, in result
hass_1       |     raise self._exception
hass_1       |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
hass_1       |     result = self.fn(*self.args, **self.kwargs)
hass_1       |   File "/usr/src/app/homeassistant/components/elkm1.py", line 167, in setup
hass_1       |     pyelk_instance.callback_add(bound_event_callback)
hass_1       | AttributeError: 'Elk' object has no attribute 'callback_add'
hass_1       | , source=components/elkm1.py>
```

**Comment by BioSehnsucht** [comment]
Strange, seems like it's not picking up the required version of PyElk (0.2.0-dev20) ?

If you look in your `config/deps/lib/python3.6/site-packages/` what PyElk directories do you see? Should see `PyElk` and `PyElk-0.2.0.dev20.dist-info`

**Comment by jshank** [comment]
What is the correct command to get that installed? I'm just using `pip install PyElk`
```
/config/deps/lib/python3.6/site-packages# ls
PyElk  PyElk-0.1.8.dev3.dist-info
```

**Comment by jshank** [comment]
I found it. I was downgrading pyserial via `pip3 install --upgrade pyserial==3.2.0` to address an issue with InsteonPLM via serial.

**Comment by BioSehnsucht** [comment]
Interesting. What's the issue with InsteonPLM and newer pyserial ?

Also, normally you shouldn't need to pip install it at all - HASS should automatically handle it (elkm1.py sets the required version for it, and HASS installs it into `config/deps/...`) . But if you're manually downgrading packages maybe that interferes with it.

**Comment by jshank** [comment]
That was the second trick. I was manually installing PyElk in my Dockerfile. Removing that and the system is working without error. Below is the output from insteon-plm now that I'm not downgrading pyserial.

More here - https://github.com/nugget/python-insteonplm/issues/19

```
> 2018-03-27 14:51:57 ERROR (MainThread) [homeassistant.setup] Error during setup of component insteon_plm
> hass_1       | Traceback (most recent call last):
> hass_1       |   File "/usr/src/app/homeassistant/setup.py", line 142, in _async_setup_component
> hass_1       |     result = await component.async_setup(hass, processed_config)
> hass_1       |   File "/usr/src/app/homeassistant/components/insteon_plm.py", line 54, in async_setup
> hass_1       |     import insteonplm
> hass_1       |   File "/usr/local/lib/python3.6/site-packages/insteonplm/__init__.py", line 6, in <module>
> hass_1       |     from .connection import Connection
> hass_1       |   File "/usr/local/lib/python3.6/site-packages/insteonplm/connection.py", line 5, in <module>
> hass_1       |     import serial.aio
> hass_1       |   File "/config/deps/lib/python3.6/site-packages/serial/aio.py", line 20, in <module>
> hass_1       |     import logger
> hass_1       | ModuleNotFoundError: No module named 'logger'
> hass_1       | 2018-03-27 14:51:57 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1522187517.2370448, level=ERROR, message=Error during setup of component insteon_plm, exception=Traceback (most recent call last):
> hass_1       |   File "/usr/src/app/homeassistant/setup.py", line 142, in _async_setup_component
> hass_1       |     result = await component.async_setup(hass, processed_config)
> hass_1       |   File "/usr/src/app/homeassistant/components/insteon_plm.py", line 54, in async_setup
> hass_1       |     import insteonplm
> hass_1       |   File "/usr/local/lib/python3.6/site-packages/insteonplm/__init__.py", line 6, in <module>
> hass_1       |     from .connection import Connection
> hass_1       |   File "/usr/local/lib/python3.6/site-packages/insteonplm/connection.py", line 5, in <module>
> hass_1       |     import serial.aio
> hass_1       |   File "/config/deps/lib/python3.6/site-packages/serial/aio.py", line 20, in <module>
> hass_1       |     import logger
> hass_1       | ModuleNotFoundError: No module named 'logger'
> hass_1       | , source=deps/lib/python3.6/site-packages/serial/aio.py>
> hass_1       | 2018-03-27 14:51:57 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service=create, service_data=title=Invalid config, message=The following components and platforms could not be set up:
> hass_1       | 
> hass_1       |  - [insteon-plm](https://home-assistant.io/components/insteon_plm/)
> hass_1       | 
> hass_1       | Please check your config., notification_id=invalid_config, service_call_id=140203620458960-7>
> hass_1       | 2018-03-27 14:51:57 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: e
```

**Comment by BioSehnsucht** [comment]
Interesting. PyElk *might* work with 3.2.0 but I've "kept up with the times" as it were, and haven't tested current code against it. You could try leaving the HASS installed version of PyElk, edit the requirements line in it to be the same as insteonplm, and uninstall/install pyserial accordingly and see what happens?
