### ISSUE TITLE
JSON Exception from 'Area' causes Recorder component crash

### ISSUE THREAD

**Issue by jshank** [BioSehnsucht/ha-elkm1#8]
I've confirmed that enabling elkm1 causes the home assistant Recorder to stop capturing events. This is most likely due to the exception below. I've removed the elkm1 component and Recorder begins working properly again. 

```
2018-04-16 08:51:40 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: Object of type 'Area' is not JSON serializable
2018-04-16 08:51:40 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1523893900.5338376, level=ERROR, message=Error executing query: Object of type 'Area' is not JSON serializable, exception=, source=components/recorder/util.py>
Exception in thread Recorder:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/src/app/homeassistant/components/recorder/__init__.py", line 314, in run
    dbevent = Events.from_event(event)
  File "/usr/src/app/homeassistant/components/recorder/models.py", line 39, in from_event
    event_data=json.dumps(event.data, cls=JSONEncoder),
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/src/app/homeassistant/remote.py", line 126, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Area' is not JSON serializable
```
This may be due to discovered property. In well behaved devices, it appears to be JSON serializable, e.g.
 `Bus:Handling <Event platform_discovered[L]: service=load_platform.sensor, platform=zwave, discovered=device=139954642257512>` 
But, for all elkm1 devices, they are objects 
`Bus:Handling <Event platform_discovered[L]: service=load_platform.sensor, platform=elkm1, discovered=[<PyElk.Area.Area object at 0x7f497af9f6a0>]>`

**Comment by BioSehnsucht** [comment]
Currently in the process of switching over to a different, better (but still being fleshed out) library to talk to the Elk. Once that's done I'll figure out this recorder weirdness.

**Comment by jshank** [comment]
Fixed in https://github.com/BioSehnsucht/ha-elkm1/tree/gwww-elkm1-lib branch.
